### ISSUE TITLE
Problem with Chinese version GY-BNO080 module

### ISSUE THREAD

**Issue by sezeryalcin** [fm4dd/pi-bno080#3]
I am testing this code with Chinese board called GY-BNO080 that is popular on Ebay and Aliexpress.
I see device is detected:
root@raspberrypi:~# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- 4b -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                        

But device index is 1, not 0 so I get this error:
./getbno080 -a 0x4b -t acc 
Error failed to open I2C bus [/dev/i2c-0].

Then I change this line in header file and recompiled: (This is RPI4 with 2GB)
#define I2CBUS               "/dev/i2c-1"

Then I don't get any data:

./getbno080 -a 0x4b -t acc 
Debug: CMD reportID [F1] REPseq [00] CMD [84] CMDseq [00] RESPseq [00] R0 [00]
Debug: CMD reportID [F1] REPseq [00] CMD [84] CMDseq [00] RESPseq [00] R0 [00]
Error: Cannot read accelerometer data.

This is probably undocumented command to get euler angles:
./getbno080 -a 0x4b -t eul
Debug: CMD reportID [F1] REPseq [00] CMD [84] CMDseq [00] RESPseq [00] R0 [00]

If any ideas to try, let me know.

**Comment by sezeryalcin** [comment]
Here is more verbose data:

# ./getbno080 -v -t acc 
Debug: arg -t, value acc
Debug: ts=[1582990735] date=Sat Feb 29 15:38:55 2020
Debug: Sensor I2C address: [0x4B]
Debug: TX   5 bytes HEAD 05 00 00 01 CARGO 01
Debug: RX   5 bytes HEAD 05 80 00 07 CARGO 01 ST [0]
Debug: OK  Error list 0 entries
Debug: OK  Initialization complete
Debug: TX  21 bytes HEAD 15 00 02 01 CARGO FD 01 00 00 00 60 EA 00 00 00 00 00 00 00 00 00 00
Debug: RX  21 bytes HEAD 15 80 02 03 CARGO FC 01 00 00 00 00 7D 00 00 00 00 00 00 00 00 00 +5 more bytes ST [0]
Debug: TX   6 bytes HEAD 06 00 02 04 CARGO FE 01
Debug: RX  39 bytes HEAD 27 80 03 01 CARGO FB F6 02 00 00 01 00 02 00 CF FF 3D 07 17 06 01 +23 more bytes ST [0]
Debug: RX  21 bytes HEAD 15 80 02 05 CARGO FC 01 00 00 00 00 7D 00 00 00 00 00 00 00 00 00 +5 more bytes ST [0]
Debug: FRS feature report received, [17 bytes]
[00] [00] [00] [00]
Error: Cannot read accelerometer data.

This could very well be some incompatibility with RPI4

**Comment by fm4dd** [comment]
This program is a fragment, it does not have most of the functions implemented yet. There is only a function skeleton which I brought over from the working code of the earlier pi-bno055 program. It is is an unfinished program mostly for my own reference.  In my project I successfully implemented a different sensor, without needing fusion.

Because the BNO080 sensor operation is very different from the BNO055, it requires polling the SHTP protocol messages, that adds an extra layer of code. 

For better examples on how to access the sensor under C, its probably best to look at the code from Arduino drivers ([Sparkfun](https://github.com/sparkfun/SparkFun_BNO080_Arduino_Library), [mbed](https://os.mbed.com/users/MultipleMonomials/code/BNO080/)). There is also the vendors reference [code](https://github.com/hcrest/bno080-driver.git).

**Comment by sezeryalcin** [comment]
well, when you download and compile something, it should do at least a few basic functions which this code does not provide. I already use this sensor on Arduino and wanted to check on RPI and found this code. That's all about it.

**Comment by nafizz1410** [comment]
Hi @sezeryalcin and @fm4dd i really need help in reading this sensor with my rpi. Can you share with me the code? please I am only interested to read the gyro module. I have tried to read it since last two weeks.

Thanl you in advance
